---
all:
  hosts:
    sonar-01:
      ansible_host: 89.169.164.127
    nexus-01:
      ansible_host: 130.193.52.92
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: user
    ansible_ssh_private_key_file: /opt/ssh_keys/id_rsa
